[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "magnetics-diagnostic-analysis"
version = "0.1.0"
description = "Try to find faulty signal in diagnostics by self-supervised learning."
authors = [{ name = "Louis Brusset", email = "louis.brusset@etu.minesparis.psl.eu" }]
requires-python = ">=3.9, <3.12"    # Python 3.11 recommended
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
keywords = ["pytorch", "lstm", "vae", "anomaly-detection", "deep-learning"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "jupyterlab>=4.4.2",
    "matplotlib>=3.9.0",
    "netcdf4>=1.7.2",
    "numpy>=1.24.0,<2.3.2",
    "pandas>=2.2.0",
    "pyyaml>=6.0.1",
    "requests>=2.32.0",
    "scikit-learn>=1.5.0",
    "scipy>=1.13.0",
    "seaborn>=0.13.0",
    "tqdm>=4.67.0",
    "xarray>=2024.6.0",
    "zarr>=2.16.0",
    "fsspec>=2024.6.0",
    "s3fs>=2024.6.0",
    "torch>=2.2.0,<2.5.0",
    "ipykernel>=6.29.0",
    "psutil>=5.9.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.0",
    "pytest-cov>=4.1.0",
    "black>=24.4.0",
    "flake8>=7.0.0",
    "mypy>=1.10.0",
]

[project.urls]
Repository = "https://github.com/LouisBrusset/ITER-magnetics-diagnostic-analysis"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["magnetics_diagnostic_analysis*"]
exclude = ["tests*"]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=. --cov-report=html --cov-report=term-missing"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true